server:
  web:
    resources:
      static-locations: "file:/C:/Users/vipin/development/"
  servlet:
    context-path: /myboard
  error:
    path: /error
    whitelabel:
      enabled: false  # Disable the default error page
    include-message: always
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: codeployer@gmail.com
    password: Nipiv1989!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  data:
    mongodb:
      #uri: mongodb://cosmosrgeastusc0f3d675-784f-433e-9759db:8m9xC4DakRGbV5gWeOaOLaSPszKwQETdYjwVzmC6AsgbHo5IMrXqh43JsprmlGcGnIIdNmhhOfVZACDbXbuajw==@cosmosrgeastusc0f3d675-784f-433e-9759db.mongo.cosmos.azure.com:10255/myboard-database?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@cosmosrgeastusc0f3d675-784f-433e-9759db@
      uri: mongodb://localhost:27017/myboard
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myboard
  jackson:
    time-zone: Asia/Kolkata


logging.level.org.springframework.security: DEBUG
spring.servlet.multipart.max-file-size: 50MB
spring.servlet.multipart.e nabled: true
spring.servlet.multipart.max-request-size: 50MB

myboard:
  user:
    profile-pic-path: C:/Users/vipin/development/myboard-uploaded-data/user/profile-pic
  display:
    path: C:/Users/vipin/development/myboard-uploaded-data/display
    timeSlotInterval: 15
  board:
    path: C:/Users/vipin/development/myboard-uploaded-data/board
  map:
    radius: 100
  timeslots:
    default-duration: 60  # Duration in minutes