package com.myboard.userservice.controller.model.timeslot.response;

import lombok.Builder;
import lombok.Data;
import java.time.LocalDateTime;  // Import LocalDateTime for time representation

@Data
@Builder
public class TimeSlotBoardToBePlayed {
    private String timeslotId;
    private String boardId;
    private String displayId;
    private String boardName;
    private String displayName;
    private String boardMediaPath;  // Updated field name
    private byte[] displayQrCode;
    private String message;

    private LocalDateTime startTime;  // Start time for the board
    private LocalDateTime endTime;    // End time for the board

    // Constructor, getters, and setters will be generated by Lombok annotations
}
