spring:
  profiles:
    active: local

---

spring.config.activate.on-profile: local

    
# Local MongoDB configuration
spring.data.mongodb.uri: mongodb://username:password@localhost:27017/userdb
---

spring.config.activate.on-profile: cloud

# Azure MongoDB configuration
spring.data.mongodb.uri: <azure-mongodb-uri>