spring:
  data:
    mongodb:
      #uri: mongodb://cosmosrgeastusc0f3d675-784f-433e-9759db:8m9xC4DakRGbV5gWeOaOLaSPszKwQETdYjwVzmC6AsgbHo5IMrXqh43JsprmlGcGnIIdNmhhOfVZACDbXbuajw==@cosmosrgeastusc0f3d675-784f-433e-9759db.mongo.cosmos.azure.com:10255/myboard-database?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@cosmosrgeastusc0f3d675-784f-433e-9759db@
      uri: mongodb://localhost:27017/userdb
logging.level.org.springframework.security: DEBUG
spring.servlet.multipart.max-file-size: 50MB
spring.servlet.multipart.enabled: true
spring.servlet.multipart.max-request-size: 50MB

myboard:
  display:
    path: C:/Users/vipin/development/myboard-uploaded-data/display
  board:
    path: C:/Users/vipin/development/myboard-uploaded-data/board
  map:
    radius: 100