package com.myboard.userservice.types;

public enum APIType {

    USER_SIGNUP,
    USER_LOGIN,
    USER_DELETE,
    USER_SAVE,
    USER_UPDATE,

    BOARD_SAVE,
    BOARD_DELETE,
    BOARD_UPDATE,
    BOARD_GET,
    BOARD_APPROVAL,

    DISPLAY_SAVE,
    DISPLAY_DELETE,
    DISPLAY_UPDATE,
    DISPLAY_GET,
    DISPLAY_GET_TIMESLOTS,
    DISPLAY_UPDATE_TIMESLOTS,
    DISPLAY_APPROVAL
}
